import 'dart:typed_data';

import 'package:lumen_core/lumen_core.dart';
import 'package:test/test.dart';

import 'preset_fixtures.dart';

void main() {
  var n = 0;
  String newId() => 'look.${n++}';
  final now = DateTime.utc(2026, 10, 7);

  LookImportResult run(List<LookImportFile> files) =>
      importLookFiles(files, inflate: inflateRaw, newId: newId, now: now);

  test('file kinds by extension', () {
    expect(lookFileKind('a.XMP'), LookFileKind.xmp);
    expect(lookFileKind('b.lrtemplate'), LookFileKind.lrtemplate);
    expect(lookFileKind('c.Cube'), LookFileKind.cube);
    expect(lookFileKind('d.zip'), LookFileKind.zip);
    expect(lookFileKind('e.jpg'), isNull);
    expect(lookFileKind('noext'), isNull);
    expect(isLookFile('x.cube'), isTrue);
  });

  test('single files: presets keep their name, group and report', () {
    final r = run([
      LookImportFile('Bright.xmp', bytesOf(kBrightAiryXmp)),
      LookImportFile('Moody Film.lrtemplate', bytesOf(kMoodyFilmLrTemplate)),
      LookImportFile('BW.xmp', bytesOf(kBwXmp)),
    ]);
    expect(r.failures, isEmpty);
    expect(r.presets.map((p) => p.name), [
      'Bright & Airy Wedding',
      'Moody Film',
      'Classic B&W',
    ]);
    final bright = r.presets.first;
    expect(bright.group, 'Weddings');
    expect(bright.source, PresetSource.lightroom);
    expect(bright.importReport!.fileName, 'Bright.xmp');
    expect(bright.createdAt, now);
    expect(r.presets[1].group, 'Imported');
    expect(r.presets[2].treatment, Treatment.bw);
    expect(r.presetCount, 3);
    expect(r.headline, '3 presets imported');
    final line = skippedLine(bright)!;
    expect(line, startsWith('5 settings in “Bright & Airy Wedding” have no'));
    expect(line, contains('Calibration'));
  });

  test('a .cube becomes a LUT look; identical tables are stored once', () {
    final lut = tealOrangeLut();
    final r = run([
      LookImportFile('teal.cube', bytesOf(lut.toCubeText())),
      LookImportFile('copy.cube', bytesOf(lut.renamed('Other').toCubeText())),
    ]);
    expect(r.presets, hasLength(2));
    expect(r.luts, hasLength(1));
    final look = r.presets.first;
    expect(look.isLutOnly, isTrue);
    expect(look.source, PresetSource.lut);
    expect(look.name, 'Teal & Orange');
    expect(look.lut!.hash, lut.contentHash);
    expect(look.lut!.amount, 100);
    expect(look.group, 'LUTs');
    expect(r.lutCount, 2);
    expect(r.headline, '2 LUTs imported');
    expect(skippedLine(look), isNull);
  });

  test('a LUT without a useful title is named after its file', () {
    final text = CubeLut.identity(3).renamed('Generated by Resolve');
    final r = run([
      LookImportFile('Kodak 2383.cube', bytesOf(text.toCubeText())),
    ]);
    expect(r.presets.single.name, 'Kodak 2383');
  });

  test('zip folders become groups; one wrapping folder is dropped', () {
    final zip = buildZip({
      'Wedding Pack/Portraits/Soft.xmp': bytesOf(kBrightAiryXmp),
      'Wedding Pack/Film/Moody.lrtemplate': bytesOf(kMoodyFilmLrTemplate),
      'Wedding Pack/Film/Teal.cube': bytesOf(tealOrangeLut().toCubeText()),
      'Wedding Pack/Broken.xmp': bytesOf(kNotAPresetXmp),
      '__MACOSX/Wedding Pack/._Soft.xmp': bytesOf('junk'),
    });
    final r = run([LookImportFile('Wedding Pack.zip', zip)]);
    expect(r.presets.map((p) => '${p.group}/${p.name}'), [
      'Portraits/Bright & Airy Wedding',
      'Film/Moody Film',
      'Film/Teal & Orange',
    ]);
    expect(
      r.failures.single.fileName,
      'Wedding Pack.zip › Wedding Pack/Broken.xmp',
    );
    expect(
      r.headline,
      '2 presets imported · 1 LUT imported · 1 file not imported',
    );
  });

  test('files at the root of a zip are grouped by the zip name', () {
    final zip = buildZip({'Soft.xmp': bytesOf(kBrightAiryXmp)});
    final r = run([LookImportFile('My Looks.zip', zip)]);
    expect(r.presets.single.group, 'My Looks');
  });

  test('bad input never throws: every file is reported', () {
    final r = run([
      LookImportFile('photo.jpg', bytesOf('x')),
      LookImportFile('evil.xmp', bytesOf(kXxeXmp)),
      LookImportFile('evil.lrtemplate', bytesOf(kEvilLrTemplate)),
      LookImportFile('bad.cube', bytesOf('LUT_3D_SIZE 2\n0 0 0\n')),
      LookImportFile('bad.zip', bytesOf('not a zip archive, only text here')),
      LookImportFile('empty.zip', buildZip({'readme.txt': bytesOf('hi')})),
      LookImportFile(
        'nested.zip',
        buildZip({
          'inner.zip': buildZip({'a.xmp': bytesOf(kBwXmp)}),
        }),
      ),
      LookImportFile('lens.xmp', bytesOf(_lensOnly)),
    ]);
    expect(r.presets, isEmpty);
    expect(r.failures, hasLength(8));
    expect(r.failures.first.reason, 'Not a preset or LUT file.');
    expect(r.failures[1].reason, contains('DOCTYPE'));
    expect(r.failures.last.reason, contains('Lens profile'));
    expect(r.headline, '8 files not imported');
    expect(
      importLookFiles(const [], inflate: inflateRaw, newId: newId).headline,
      'Nothing to import',
    );
  });

  test('oversized files are refused before reading', () {
    final big = bytesOf(
      'x' * (kLookFileMaxBytes[LookFileKind.lrtemplate]! + 1),
    );
    final r = run([LookImportFile('big.lrtemplate', big)]);
    expect(r.failures.single.reason, 'The file is too large.');
  });

  test('UTF-16 and BOM text', () {
    final units = '﻿$kBwXmp'.codeUnits;
    final le = [
      for (final u in units) ...[u & 0xff, u >> 8],
    ];
    expect(decodeLookText(Uint8List.fromList(le)), kBwXmp);
    final be = [
      for (final u in units) ...[u >> 8, u & 0xff],
    ];
    expect(decodeLookText(Uint8List.fromList(be)), kBwXmp);
    expect(decodeLookText(bytesOf('﻿abc')), 'abc');
  });
}

const _lensOnly = '''<x:xmpmeta xmlns:x="adobe:ns:meta/">
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"
 crs:LensProfileEnable="1" crs:AutoLateralCA="1" crs:Version="15.4"/>
</rdf:RDF></x:xmpmeta>''';
