import 'param_registry.dart';
import 'preset.dart';
import 'tone_curve.dart';
import 'treatment.dart';

ParamId _h(HslBand b, HslChannel c) => P.hsl(b, c);

/// The 12 built-in looks (values derived from the style atoms in research 01 §7.3).
final List<Preset> kBuiltinPresets = List.unmodifiable([
  Preset(
    id: 'builtin.natural_lift',
    name: 'Natural Lift',
    group: 'Essentials',
    builtIn: true,
    values: {
      P.exposure: 0.15,
      P.shadows: 20,
      P.highlights: -15,
      P.vibrance: 10,
      P.clarity: 5,
    },
  ),
  Preset(
    id: 'builtin.bright_airy',
    name: 'Bright & Airy',
    group: 'Essentials',
    builtIn: true,
    values: {
      P.exposure: 0.4,
      P.contrast: -10,
      P.highlights: -20,
      P.shadows: 25,
      P.whites: 10,
      P.blacks: 10,
      P.vibrance: 5,
      _h(HslBand.orange, HslChannel.lum): 5,
    },
  ),
  Preset(
    id: 'builtin.moody',
    name: 'Moody',
    group: 'Creative',
    builtIn: true,
    values: {
      P.exposure: -0.3,
      P.highlights: -25,
      P.shadows: -5,
      P.blacks: -10,
      P.vibrance: -15,
      P.saturation: -5,
      P.temp: -5,
      P.vignetteAmount: -15,
      P.grade(GradeZone.shadows, 'hue'): 215,
      P.grade(GradeZone.shadows, 'sat'): 10,
    },
  ),
  Preset(
    id: 'builtin.punchy',
    name: 'Punchy',
    group: 'Essentials',
    builtIn: true,
    values: {
      P.contrast: 20,
      P.whites: 8,
      P.blacks: -8,
      P.clarity: 8,
      P.vibrance: 10,
    },
  ),
  Preset(
    id: 'builtin.soft_matte',
    name: 'Soft Matte',
    group: 'Creative',
    builtIn: true,
    values: {P.contrast: -15, P.highlights: -15, P.shadows: 15, P.clarity: -10},
    curves: const CurveSet(
      master: ToneCurve([CurvePoint(0, 18), CurvePoint(255, 255)]),
    ),
  ),
  Preset(
    id: 'builtin.cinematic',
    name: 'Cinematic Teal-Orange',
    group: 'Creative',
    builtIn: true,
    values: {
      P.contrast: 10,
      P.blacks: 6,
      P.grade(GradeZone.shadows, 'hue'): 200,
      P.grade(GradeZone.shadows, 'sat'): 15,
      P.grade(GradeZone.highlights, 'hue'): 40,
      P.grade(GradeZone.highlights, 'sat'): 12,
      _h(HslBand.blue, HslChannel.hue): -10,
      _h(HslBand.orange, HslChannel.sat): 5,
      P.vibrance: -5,
      P.vignetteAmount: -10,
    },
  ),
  Preset(
    id: 'builtin.faded_film',
    name: 'Faded Film',
    group: 'Film',
    builtIn: true,
    values: {
      P.contrast: -10,
      P.saturation: -10,
      P.grade(GradeZone.highlights, 'hue'): 45,
      P.grade(GradeZone.highlights, 'sat'): 10,
      P.grainAmount: 20,
      P.vignetteAmount: -8,
    },
    curves: const CurveSet(
      master: ToneCurve([
        CurvePoint(0, 20),
        CurvePoint(64, 60),
        CurvePoint(192, 200),
        CurvePoint(255, 245),
      ]),
    ),
  ),
  Preset(
    id: 'builtin.golden_hour',
    name: 'Golden Hour',
    group: 'Creative',
    builtIn: true,
    values: {
      P.temp: 20,
      P.tint: 5,
      P.grade(GradeZone.highlights, 'hue'): 40,
      P.grade(GradeZone.highlights, 'sat'): 15,
      _h(HslBand.orange, HslChannel.sat): 10,
      _h(HslBand.yellow, HslChannel.sat): 5,
      P.highlights: -10,
    },
  ),
  Preset(
    id: 'builtin.crisp_landscape',
    name: 'Crisp Landscape',
    group: 'Essentials',
    builtIn: true,
    values: {
      P.contrast: 12,
      P.highlights: -30,
      P.shadows: 20,
      P.clarity: 15,
      P.dehaze: 10,
      P.vibrance: 15,
      _h(HslBand.blue, HslChannel.sat): 12,
      _h(HslBand.blue, HslChannel.lum): -10,
      _h(HslBand.green, HslChannel.sat): 5,
      P.sharpenAmount: 40,
    },
  ),
  Preset(
    id: 'builtin.clean_product',
    name: 'Clean Product',
    group: 'Commerce',
    builtIn: true,
    values: {
      P.exposure: 0.3,
      P.whites: 25,
      P.blacks: -5,
      P.contrast: 8,
      P.clarity: 5,
      P.vibrance: 5,
      P.sharpenAmount: 50,
    },
  ),
  Preset(
    id: 'builtin.classic_bw',
    name: 'Classic B&W',
    group: 'Black & white',
    builtIn: true,
    values: {P.contrast: 15, P.bw(HslBand.blue): -20, P.bw(HslBand.orange): 10},
    treatment: Treatment.bw,
  ),
  Preset(
    id: 'builtin.high_contrast_bw',
    name: 'High-Contrast B&W',
    group: 'Black & white',
    builtIn: true,
    values: {
      P.contrast: 40,
      P.whites: 20,
      P.blacks: -25,
      P.clarity: 20,
      P.bw(HslBand.blue): -35,
      P.grainAmount: 12,
    },
    treatment: Treatment.bw,
  ),
]);
